name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Thiagoprioto
          outputs: |
            dist/snake.svg

      - name: Upload Snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "update snake"
          add: "dist/snake.svg"

